# Build numbering format
name: $(BuildID)

# Trigger
# -------

trigger:
  branches:
    include:
    - master
    - feat/*
    - refactor/*
    - release


# Shared Templates
# ----------------

resources:
  repositories:
    - repository: templates
      type: github
      name: julie-ng/azure-pipelines-templates
      endpoint: julie-ng # required, even if public repo
      ref: refs/tags/v1.1.1

# Schedule
# ---------

schedules:
- cron: "0 0 * * Mon"
  displayName: Weekly midnight build
  always: true
  branches:
    include:
    - master
    - releases/*


# Variables
# ---------

variables:
  - group: azure-demos-config

  - name: app-name
    value: oidc-demo

  - name: image-tag
    value: 'dev'

  - name: image-name
    value: $(lib-var-registry-namespace)/$(app-name)

  - name: image-name-with-registry
    value: $(lib-var-registry-host)/$(image-name)

  - name: is-dev
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }}

  - name: is-release
    value: ${{ and(eq(variables['Build.SourceBranch'], 'refs/heads/release'), ne(variables['Build.Reason'], 'Schedule')) }}

# Stages
# ---------

stages:

# --- Stage: Test ---

- stage: Tests
  displayName: 'Test (Node.js)'
  jobs:
    - job: Audit
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm audit
        displayName: Audit Dependencies (all)
        continueOnError: true

      - script: npm audit --production
        displayName: Audit Dependencies (prod-only)
        continueOnError: false

    - job: Linter
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm ci && npm run lint
        displayName: Lint Code


# --- Stage: Build and Push Docker image ---

- stage: BuildImage
  displayName: 'Build (Docker)'
  jobs:
    - job: build_and_push
      displayName: 'Build and Push Image'

      steps:
      - template: steps/set-custom-variable.yml@templates
        parameters:
          variableName: image-tag
          command: 'npm run --silent my-version'
          condition: $(is-release)

      - template: steps/docker-build-push.yml@templates
        parameters:
          registryConnectionName: $(var-registry-connection)
          imageName: $(image-name)
          tagsAsMultilineString: |
            $(image-tag)

      # lock release images
      - task: AzureCLI@2
        displayName: 'Lock release image, preventing delete'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'), ne(variables['Build.Reason'], 'Schedule'))
        inputs:
          azureSubscription: $(lib-var-az-acr-connection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
              az --version
              az acr repository update \
                --name $(lib-var-acr-name) --image $(image-name):$(image-tag) \
                --write-enabled false


# --- Stage: deploy to Azure App Services ---

- stage: DeployImage
  displayName: Deploy
  jobs:

  - job: deploy_master
    displayName: 'Deploy (master)'
    condition: $(is-dev)
    steps:
      - template: steps/deploy-app-service.yml@templates
        parameters:
          ARMConnectionName: $(var-arm-connection)
          dockerImage: $(image-name-with-registry):$(image-tag)
          appName: $(app-name)-dev # with `-dev` suffix


  - job: deploy_release
    displayName: 'Deploy (release)'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'), ne(variables['Build.Reason'], 'Schedule'))
    steps:
      # Override image tag with versioned release tag
      - template: steps/set-custom-variable.yml@templates
        parameters:
          variableName: image-tag
          command: 'npm run --silent my-version'

      - template: steps/deploy-app-service.yml@templates
        parameters:
          ARMConnectionName: $(var-arm-connection)
          dockerImage: $(image-name-with-registry):$(image-tag)
          appName: $(app-name)
