# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
    - master
    - feat/*

schedules:
- cron: "0 0 * * Mon"
  displayName: Weekly midnight build
  always: true
  branches:
    include:
    - master
    - releases/*

variables:
  - group: azure-demos-config
  - name: repository
    value: $(registry-host)/$(registry-namespace)
  - name: image-name
    value: $(repository)/$(app-name)
  - name: image-tag
    value: $(Build.BuildId)-$(Build.SourceVersion)

stages:
- stage: Tests
  displayName: 'Test (Node.js)'
  jobs:
    - job: Audit
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm audit
        displayName: Audit Dependencies
        continueOnError: true

    - job: Linter
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - script: npm ci && npm run lint
        displayName: Lint Code


# ----------------------------
# Docker Image: Build and Push
# ----------------------------

- stage: BuildImage
  displayName: 'Build (Docker)'
  jobs:
    - job: build_and_push_image
      displayName: Build and Push Image
      steps:

      - script: docker build --tag $(image-name):$(image-tag) .
        displayName: 'Docker: Build and tag image'

      - task: Docker@1
        displayName: 'Push an image'
        inputs:
          azureSubscriptionEndpoint: $(registry-service-connection)
          azureContainerRegistry: $(registry-host)
          imageName: $(image-name):$(image-tag)
          command: push

# ----------------------------
# Deploy to Azure App Services
# ----------------------------

- stage: DeployImage
  displayName: Deploy
  jobs:
  - job: deploy_image
    displayName: 'Deploy Image (master)'
    steps:
    - task: AzureWebAppContainer@1
      displayName: Deploy container as Azure Web App
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')) # (master branch and succesful builds only)
      inputs:
        appName: $(appservice-name)
        azureSubscription: $(appservice-service-connection)
        imageName: $(image-name):$(image-tag)