version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      PORT: 3000
      # REDIS_HOST: redis
      # REDIS_PORT: '6379'
      # REDIS_PASSWORD: ''
    depends_on:
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ./app:/workspace/app
  redis:
    image: redis:4 # Azure cache version
    expose:
      - '6379'
