version: '3'
services:
  app:
    build: .
    command: npm start
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      PORT: 3000
    depends_on:
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ./app:/workspace/app
  redis:
    image: redis:latest
    expose:
      - '6379'
